name: automatedabstraction
channels:
  - conda-forge
dependencies:
  - loguru=0.7.2
  - numpy=2.0.0
  - pandas=2.2.2
  - pip=24.0
  - pytest=8.3.1
  - python=3.12.4
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - statsmodels=0.14.2
  - tqdm=4.66.4